### PR TITLE
Add wilson dataset

### PR DESCRIPTION
**Pull request by GerbrichFerdinands**
Add dataset from systematic review on Wilson disease + preprocessing scripts. 

Original dataset via:
Appenzeller-Herzog, C. (2020). Data from Comparative effectiveness of common therapies for Wilson disease: A systematic review and meta‐analysis of controlled studies. https://doi.org/10.5281/zenodo.3625931

Publication: 
Appenzeller‐Herzog, C., Mathes, T., Heeres, M. L. S., Weiss, K. H., Houwen, R. H. J., & Ewald, H. (2019). Comparative effectiveness of common therapies for Wilson disease: A systematic review and meta-analysis of controlled studies. Liver International, 39(11), 2136–2152. https://doi.org/10.1111/liv.14179

### CODE REVIEW

**Comment by J535D165** [comment]
Thanks thanks thanks. Great to have this PR. I made a couple of changes to fix the issues with the RIS parsing. We can now bypass the Zotero step :) The README is now a bit outdated.

**Comment by J535D165** [comment]
@terrymyc Please have a lot at this PR. It might be useful for the other pipelines as well.

**Comment by GerbrichFerdinands** [comment]
Thank you for the nice adjustments!
And by the way thanks to @boer0107 for letting me know about this dataset!

**Comment by GerbrichFerdinands** [comment]
I updated the readme. Also, I noted ``label_included`` contains 1s and NaN's. I added a line to convert the NaN's into 0s. Might be a bit hacky though! Could you take a look @J535D165 ?

**Comment by J535D165** [comment]
Thanks, @GerbrichFerdinands. Teamwork and a great example to others ;) 

Looking forward to seeing the simulation results of this dataset.

@Rensvandeschoot

**Comment by Rensvandeschoot** [comment]
Well done everyone!

**Pull request merged**
