### PR TITLE
Correct citation

### PR DESCRIPTION
**Pull request by GerbrichFerdinands**
Found a mismatch between inclusions in the paper (n=106) and inclusions in the final dataset (n=104). 
Thanks to @azhe825, first author, who pointed out that we are referring to an unpublished version of the paper. 
Hereby I add the correct citation (with n=104).

### CODE REVIEW

**Comment by J535D165** [comment]
Thanks @GerbrichFerdinands and @azhe825

**Comment by azhe825** [comment]
@GerbrichFerdinands @J535D165 
There is yet another dataset created by our team at
[https://github.com/fastread/SLR_on_TCP](https://github.com/fastread/SLR_on_TCP)

The associated paper is not published yet but available at [arxiv](https://arxiv.org/abs/1909.07249)

**Comment by Rensvandeschoot** [comment]
Well spotted!! And thanks for explaining this difference!

**Comment by J535D165** [comment]
Thanks @azhe825. We will have a look!

**Pull request merged**
