### PR TITLE
Restructure repository and label duplicates

### PR DESCRIPTION
**Pull request by terrymyc**
The processing of most datasets is renewed. A (sort of) same workflow is applied to the processing of datasets.
- All output `.csv` files have `record_id`
- Duplicates are detected based on title and/or authors
- Duplicates are labeled by a new column `duplicate_record_id`, and not removed from an output file
- The original order of rows in a dataset is kept

### CODE REVIEW

**Comment by GerbrichFerdinands** [comment]
Great work @terrymyc! I'll have a closer look next week. 
Do you know if `label_abstract_included` is compatible with the simulation mode? Until now, I've only seen `abstract_included`.

**Comment by terrymyc** [comment]
Not sure. Here I use `label_abstract_screening` that comes from Wilson dataset processing you made before.

**Comment by GerbrichFerdinands** [comment]
> Not sure. Here I use `label_abstract_screening` that comes from Wilson dataset processing you made before.

Whoops, my bad! The allowed names are  "abstract_included", "included_abstract", and "included_after_abstract".  I found them in the `config.py` file: 

```
COLUMN_DEFINITIONS = [
    ["final_included", "label", "label_included", "included_label",
     "included_final", "included", "included_flag", "include"],
    ["abstract_included", "included_abstract", "included_after_abstract"],
    ['title', 'primary_title'],
    ['authors', 'author names', 'first_authors'],
    ['abstract', 'abstract note'],
    ['keywords'],
]
```

**Comment by terrymyc** [comment]
Okay, shall we add `label_abstract_screening` to `config.py`, or replace it with `abstract_included`?

**Comment by GerbrichFerdinands** [comment]
> Okay, shall we add `label_abstract_screening` to `config.py`, or replace it with `abstract_included`?

Let's replace it with `abstract_included` and keep using that term in this repository consistently.

**Comment by J535D165** [comment]
Hi @terrymyc, really nice PR! 

Two remarks:
- Deduplication methods can change over time. For example, because we are able to improve them. This will effect all the simulation results downstream as well as in publications. We think it is a good idea to assure the number of records in the processed dataset equals the number of record in the original dataset. The deduplication should be an additional column in the output. This can be a flag or a reference to the first record of the cluster of duplicates in the dataset. Does this make sense to you? Users can easily filter on this column to filter if they like. This can be useful for the simulation part of the project. 
- I like the renaming of folders. Can you replace all special characters by `_`? Like `datasets/Kwok_et_al_2020/README.md`. We need to have a check what downstream applications will break. 

Those remarks are relevant for #25 as well. Would you like me to merge #25 first?

**Comment by terrymyc** [comment]
> The deduplication should be an additional column in the output. Users can easily filter on this column to filter if they like. This can be useful for the simulation part of the project.

Makes sense. Maybe an additional column `label_duplicated` with values `1` and `0` indicating whether the record is duplicated or not?

> Those remarks are relevant for #25 as well. Would you like me to merge #25 first?

Regarding this dataset processing workflow, I'm not sure if it is proper to remove local `raw` data and retrieve them from PubMed since it takes several hours. What do you think?

**Comment by terrymyc** [comment]
@J535D165 @GerbrichFerdinands This PR is ready!!

**Review by J535D165 — APPROVED** [review]

**Comment by J535D165** [comment]
Great! You did a great job, but this is worth all the effort. You do have a great feeling for detail! I will merge this and update the datasets in https://github.com/asreview/asreview/tree/master/tests/test_datasets and https://github.com/asreview/asreview/tree/master/datasets.

**Comment by Rensvandeschoot** [comment]
WOW!!! This is really good work @terrymyc !!!! It was a lot of work and not easy at all, but you managed! This shows your excellent skills! Glad you are in our team!!

**Comment by GerbrichFerdinands** [comment]
Hi @terrymyc, great work! You've laid a solid foundation for all future simulation studies. 
Thank you very much for the hard work! 💪

**Comment by terrymyc** [comment]
My pleasure! Please also watch the performance of updated datasets. Since the processing involves a lot and different details in different datasets, there might still be something I neglect...

**Comment by GerbrichFerdinands** [comment]
Thanks, maybe @LHofstee can make a comparison for a couple of datasets?

**Comment by J535D165** [comment]
Sounds like a plan. I'm assigning a different task to her first (extend the metadata about the datasets and make it machine readable). Maybe she can work on this at the same time.

**Comment by LHofstee** [comment]
@GerbrichFerdinands @J535D165 I will work on both of them! The comparison is an extension of what I'm already working on.

**Pull request merged**
